### ISSUE TITLE
Travis build failing with timeout

### ISSUE THREAD

**Issue by thijslemmens** [thijslemmens/carbon-postgres#5]
eu.thijslemmens.carbonpostgres.db.DbQueueSpec > A DbQueue must batch when writing to a slow db FAILED
    java.util.concurrent.TimeoutException: Futures timed out after [20 seconds]
        at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
        at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
        at scala.concurrent.Await$.$anonfun$result$1(package.scala:215)
        at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
        at scala.concurrent.Await$.result(package.scala:142)
        at eu.thijslemmens.carbonpostgres.db.DbQueueSpec.$anonfun$new$3(DbQueueSpec.scala:44)
eu.thijslemmens.carbonpostgres.db.DbQueueSpec STANDARD_OUT
    [INFO] [01/30/2018 19:56:40.661] [testActorSystem-akka.actor.default-dispatcher-7] [akka://testActorSystem/user/$b] Message [eu.thijslemmens.carbonpostgres.Record] from Actor[akka://testActorSystem/temp/$a] to Actor[akka://testActorSystem/user/$b#1031525703] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Gradle Test Executor 2 finished executing tests.

**Comment by thijslemmens** [comment]
The build is working on my local machine. On travis, it does not work, even if I put a timeout of 2 minutes.
